name = "Step 5 Preview"
description = "StepFun flash model for efficient multimodal reasoning, coding, and tool use"
family = "step"
release_date = "2026-09-20"
last_updated = "2026-09-20"
attachment = true
reasoning = false
tool_call = false
open_weights = false

[cost]
input = 1
output = 2.7
cache_read = 0.05

[limit]
context = 1_000_000
output = 1_000_000

[modalities]
input = ["text", "image"]
output = ["text"]
