base_model = "nvidia/nemotron-3-super-120b-a12b"
name = "Nemotron-3-Super-120B-A12B"
last_updated = "2026-03-12"
structured_output = true
knowledge = "2026-02"
reasoning_options = []

[cost]
input = 0.3
output = 0.9

[limit]
input = 262_144
output = 32_768
